### ISSUE TITLE
Make it possible to use models without headers for feature extraction

### ISSUE THREAD

**Issue by hadipash** [mindspore-lab/mindcv#454] opened 2023-02-15 07:56 UTC
Make it possible to use MindCV models for feature extraction easily by adding a parameter that allows to initialize networks without headers. Can use [TF implementation](https://github.com/keras-team/keras/blob/e6784e4302c7b8cd116b74a784f4b78d60e83c26/keras/applications/resnet.py#L76) for reference (the `include_top` parameter).

A possible implementation example based on ResNet could be:
```python
class ResNet(nn.Cell):
    def __init__(self,
                 block: Type[Union[BasicBlock, Bottleneck]],
                 layers: List[int],
                 num_classes: int = 1000,
                 in_channels: int = 3,
                 groups: int = 1,
                 base_width: int = 64,
                 norm: Optional[nn.Cell] = None,
                 include_top: bool = True
                 ) -> None:
        super().__init__()
        ...
        if include_top:
            self.pool = GlobalAvgPooling()
            self.num_features = 512 * block.expansion
            self.classifier = nn.Dense(self.num_features, num_classes)
        else:
            # add averaging options here
    ...
    def construct(self, x: Tensor) -> Tensor:
        x = self.forward_features(x)
        if self.include_top:
            x = self.forward_head(x)
        return x
````

This will allow to re-use models implemented in MindCV as backbones in different tasks easily.

**Comment by geniuspatrick** [comment] 2023-06-13 06:36
duplicate of #626

**Closed by geniuspatrick** 2023-06-13 06:36 UTC
Labels: rfc
